[profile.default]
src = "src"
out = "out"
libs = ["src/libraries", "lib"]
allow_paths = ["node_modules"]
remappings = ["@uniswap/=node_modules/@uniswap/"]

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
